config/routes.rb
Flixter4::Application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :courses, only: [:index, :show]
  namespace :instructor do
    resources :courses, only: [:new, :create, :show]
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :courses 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @course = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  def new
    @course = Course.new 
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity  
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  private

  def course_params
    params.require(:course).permit(:title, :description, :cost)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />

  <% @course.each do |course| %>
    <h2 class="text-center">
      <%= link_to course.title, course_path(course) %>
    </h2>
    <br />
    <div class="col-sm-8 col-xs-12">
      <%= course.description %>
    </div>
    <div class="col-sm-4 col-xs-12 text-center">
      <%= link_to 'More details...', course_path(course), class: 'btn btn-primary btn-large' %>
    </div>
    <br class="clr" />
  <% end %>
</div>

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1><%= @course.title %></h1>
  <br />
  <div class="col-sm-4 col-xs-12 text-center">
    <span class="label label-default">
      <%= number_to_currency @course.cost %>
    </span>

    <% if current_user && current_user == @course.user %>
    <br />
    <br />
    <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
    <% end %>
  </div>

  <div class="col-sm-8 col-xs-12">
    <%= @course.description %>
  </div>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center"><%= @course.title %><h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flixter4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="#">Flixter</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'See all courses', courses_path %>
            </li>
            <li><a href="#">Link</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
            <li><a href="#">Link</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>

  <br class="clr"/>

  <div id="footer">
    <div class="container">
      <b>Teachers</b>
      <br />
      <%= link_to 'Teach a course', new_instructor_course_path %>
    </div>
  </div>

</body>
</html>

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class ="frosty col-xs-10 col-xs-offset-1 text-center">
    <br />
    <h1>Learn something new today!</h1>
    <br />    
    <h3>New content added daily</h3>
    <br />    
    <%= link_to 'Learn more', courses_path, class: "btn btn-success" %>
    <br /><br />    
  </div>
</div>
<br />
<div class="col-xs-10 col-xs-offset-1 features text-center">
  <div class="col-sm-4">
    <h3>Feature 1</h3>
  </div>

  <div class="col-sm-4">
    <h3>Feature 2</h3>
  </div>

  <div class="col-sm-4">
    <h3>Feature 3</h3>
  </div>
</div>